<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <ProjectReference Include="../../src/IndefiniteError.AspNetCore/IndefiniteError.AspNetCore.csproj" />
  </ItemGroup>

</Project>
