<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <PropertyGroup>
    <Version>0.1.0</Version>
    <Authors>Tomperez98</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/Tomperez98/indefinite-error</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Tomperez98/indefinite-error</RepositoryUrl>
    <PackageTags>testing;fault-injection;indefinite-errors;idempotency;aspnetcore</PackageTags>
  </PropertyGroup>

</Project>
